[2024-06-13T04:49:23.948+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: tourism_data_pipeline.get_data_from_API manual__2024-06-13T04:49:18.382206+00:00 [queued]>
[2024-06-13T04:49:24.047+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: tourism_data_pipeline.get_data_from_API manual__2024-06-13T04:49:18.382206+00:00 [queued]>
[2024-06-13T04:49:24.048+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-06-13T04:49:24.048+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-06-13T04:49:24.048+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-06-13T04:49:24.155+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): get_data_from_API> on 2024-06-13 04:49:18.382206+00:00
[2024-06-13T04:49:24.189+0000] {standard_task_runner.py:55} INFO - Started process 377 to run task
[2024-06-13T04:49:24.213+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'tourism_data_pipeline', 'get_data_from_API', 'manual__2024-06-13T04:49:18.382206+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/scraping-tourism-API.py', '--cfg-path', '/tmp/tmprx5yrhpv']
[2024-06-13T04:49:24.229+0000] {standard_task_runner.py:83} INFO - Job 9: Subtask get_data_from_API
[2024-06-13T04:49:26.277+0000] {task_command.py:388} INFO - Running <TaskInstance: tourism_data_pipeline.get_data_from_API manual__2024-06-13T04:49:18.382206+00:00 [running]> on host 557189db82cf
[2024-06-13T04:49:26.673+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=sangmin
AIRFLOW_CTX_DAG_ID=tourism_data_pipeline
AIRFLOW_CTX_TASK_ID=get_data_from_API
AIRFLOW_CTX_EXECUTION_DATE=2024-06-13T04:49:18.382206+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-06-13T04:49:18.382206+00:00
[2024-06-13T04:49:26.708+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:313: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-13T04:49:27.403+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/scraping-tourism-API.py", line 113, in get_data_from_API
    raise Exception(error_message)
Exception: dag_id : tourism_data_pipeline
task : get_data_from_API
Error : Tourism API does not have data in 20240613 ~ 20240613


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scraping-tourism-API.py", line 131, in get_data_from_API
    raise Exception(error_message)
Exception: dag_id : tourism_data_pipeline
task : get_data_from_API
Error : API Data Processing Error
Comment : dag_id : tourism_data_pipeline
task : get_data_from_API
Error : Tourism API does not have data in 20240613 ~ 20240613

[2024-06-13T04:49:27.419+0000] {taskinstance.py:1318} INFO - Marking task as FAILED. dag_id=tourism_data_pipeline, task_id=get_data_from_API, execution_date=20240613T044918, start_date=20240613T044923, end_date=20240613T044927
[2024-06-13T04:49:27.794+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 9 for task get_data_from_API (dag_id : tourism_data_pipeline
task : get_data_from_API
Error : API Data Processing Error
Comment : dag_id : tourism_data_pipeline
task : get_data_from_API
Error : Tourism API does not have data in 20240613 ~ 20240613
; 377)
[2024-06-13T04:49:27.830+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-06-13T04:49:27.874+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
