[2024-06-13T05:50:01.992+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: tourism_data_pipeline.get_data_from_API scheduled__2024-06-13T05:40:00+00:00 [queued]>
[2024-06-13T05:50:02.008+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: tourism_data_pipeline.get_data_from_API scheduled__2024-06-13T05:40:00+00:00 [queued]>
[2024-06-13T05:50:02.008+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-06-13T05:50:02.008+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-06-13T05:50:02.008+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-06-13T05:50:02.034+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): get_data_from_API> on 2024-06-13 05:40:00+00:00
[2024-06-13T05:50:02.045+0000] {standard_task_runner.py:55} INFO - Started process 2668 to run task
[2024-06-13T05:50:02.055+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'tourism_data_pipeline', 'get_data_from_API', 'scheduled__2024-06-13T05:40:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/scraping-tourism-API.py', '--cfg-path', '/tmp/tmptehv6b6f']
[2024-06-13T05:50:02.059+0000] {standard_task_runner.py:83} INFO - Job 24: Subtask get_data_from_API
[2024-06-13T05:50:02.540+0000] {task_command.py:388} INFO - Running <TaskInstance: tourism_data_pipeline.get_data_from_API scheduled__2024-06-13T05:40:00+00:00 [running]> on host 557189db82cf
[2024-06-13T05:50:02.701+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=sangmin
AIRFLOW_CTX_DAG_ID=tourism_data_pipeline
AIRFLOW_CTX_TASK_ID=get_data_from_API
AIRFLOW_CTX_EXECUTION_DATE=2024-06-13T05:40:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-06-13T05:40:00+00:00
[2024-06-13T05:50:02.711+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:313: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-13T05:50:04.075+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/scraping-tourism-API.py", line 112, in get_data_from_API
    raise Exception(error_message)
Exception: dag_id : tourism_data_pipeline
task : get_data_from_API
Error : Tourism API does not have data in 20240613 ~ 20240613


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scraping-tourism-API.py", line 130, in get_data_from_API
    raise Exception(error_message)
Exception: dag_id : tourism_data_pipeline
task : get_data_from_API
Error : API Data Processing Error
Comment : dag_id : tourism_data_pipeline
task : get_data_from_API
Error : Tourism API does not have data in 20240613 ~ 20240613

[2024-06-13T05:50:04.089+0000] {taskinstance.py:1318} INFO - Marking task as FAILED. dag_id=tourism_data_pipeline, task_id=get_data_from_API, execution_date=20240613T054000, start_date=20240613T055001, end_date=20240613T055004
[2024-06-13T05:50:04.448+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 24 for task get_data_from_API (dag_id : tourism_data_pipeline
task : get_data_from_API
Error : API Data Processing Error
Comment : dag_id : tourism_data_pipeline
task : get_data_from_API
Error : Tourism API does not have data in 20240613 ~ 20240613
; 2668)
[2024-06-13T05:50:04.532+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-06-13T05:50:04.918+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
